### ISSUE TITLE
Grid is not showing with large data (ex data255 in the sample page)

### ISSUE THREAD

**Issue by manuferro** [jsGanttImproved/jsgantt-improved#321] opened 2020-10-07 08:03 UTC
when we have a large Json file the grid is not showed

1. Go to sample page
2. select data255 as json data

The same happens also with other sets of data over a certain number of rows

Thanks
![image](https://user-images.githubusercontent.com/6489807/95304023-45854800-0884-11eb-95f6-a64faac03c77.png)

**Comment by agarciacalvo** [comment] 2020-10-13 18:28
I think this is related to #320 . The data still shows, but it's difficult to see because it starst on 1970:

![image](https://user-images.githubusercontent.com/18212145/95900681-89031900-0d92-11eb-8d22-a6210540d68c.png)

**Comment by agarciacalvo** [comment] 2020-10-30 09:29
Confirmed.

![image](https://user-images.githubusercontent.com/18212145/97688649-b4784a00-1a9a-11eb-8993-acb63fe42b00.png)

I think we can close this issue.

**Comment by mariohmol** [comment] 2020-10-30 13:20
With single-cell this works right?

thanks @agarciacalvo

**Closed by mariohmol** 2020-10-30 13:20 UTC
