### ISSUE TITLE
End dates do not match between what is shown on the left grid, and what is shown on the right grid

### ISSUE THREAD

**Issue by jlanao** [jsGanttImproved/jsgantt-improved#140] opened 2019-01-14 17:27 UTC
**Describe the bug**
When i see a task in the Month or Quarter Format, the end date that the task shows is about a month off of what the actual end date value is.

**To Reproduce**
1. Go to https://jsganttimproved.github.io/jsgantt-improved/demo.html
2. Make sure you have a task longer than 6 months.
3. Select the Month Format
4. See error (attached image)

**Expected behavior**
The end date should be the equivalent in both grids

**Screenshots**
Month View:
![image](https://user-images.githubusercontent.com/46685353/51129097-88250800-17f7-11e9-80a9-e493e191e559.png)

Quarterly View:
![image](https://user-images.githubusercontent.com/46685353/51129144-abe84e00-17f7-11e9-8632-3563171274cf.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mariohmol** [comment] 2019-01-18 01:43
Sorry.. i dont get it.. isnt that right?

**Comment by mariohmol** [comment] 2019-01-18 11:36
Oww ok.. now i got it... could u provide a json data to test this?

**Comment by da3x** [comment] 2019-03-06 14:36
In my case `.gantt td { padding: 1px; }` helped a little... but not in all cases.

**Comment by pozo123** [comment] 2019-03-06 17:53
I just commented on issue #48 . I believe the issue has something to do with the current date. When trying to reproduce your error it worked just fine, but I believe it is because the end date of the task you signaled was after the current date the day you posted this, and it is no longer.

**Comment by SimonRoell** [comment] 2019-04-09 08:27
Im my case, changing jsgantt.js (lines 3455 and 3456) to:
`var MONTH_CELL_MARGIN_WIDTH = 3; // Cell margin for 'month' format`
`var QUARTER_CELL_MARGIN_WIDTH = 3; // Cell margin for 'quarter' format`
solved the issue.
However I am not sure if affects other functionalities...

**Comment by mariohmol** [comment] 2019-07-27 02:19
thanks @nidu !!

this is fixed on latest version

**Closed by mariohmol** 2019-07-27 02:19 UTC
Labels: bug
